name: Commit

on: [push, pull_request, workflow_dispatch]

jobs:
  build_posix:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.16.x]
    steps:
      - uses: actions/checkout@v2
      - name: set up go ${{ matrix.version }}
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
      - name: golangci-lint
        run: golangci-lint run
      - name: tests
        run: go test -cover -v ./channel/... ./driver/... ./netconf/... ./logging/... ./transport/...
